package ui.editores;

import matr.Asignatura;
import matr.Periodo;

/**
 *
 * @author Jedabero
 */
public class AsignaturaEditor extends javax.swing.JPanel {

    private final Periodo p;
    private Asignatura a;

    /**
     * Creates new form AsignaturaEditor.
     *
     * Si <code>a</code> es null entoces se crea una nueva asignatura.
     *
     * @param a asignatura a editar
     * @param p en el que está situado la asigantura.
     */
    public AsignaturaEditor(Asignatura a, Periodo p) {
        this.a = a;
        this.p = p;
        initComponents();
        if (null != a) {
            txtNombre.setText(a.getNombre());
            txtCodigo.setText(a.getCodigo());
            jsCreditos.setValue(a.getCreditos());
            txtPeriodo.setText(a.getPeriodo());
            txtNivel.setText(a.getNivel());
            txtNota.setText("" + a.getNota());
            Asignatura r = a.getRequisito();
            txtReq.setText((r != null) ? r.getCodigo() : "");
            Asignatura cr = a.getCorequisito();
            txtCoreq.setText((null != cr) ? cr.getCodigo() : "");
        }

    }

    public AsignaturaEditor(Periodo p) {
        this(null, p);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtCodigo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jsCreditos = new javax.swing.JSpinner();
        txtPeriodo = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtReq = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtCoreq = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtNota = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtNivel = new javax.swing.JTextField();

        setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Edicion de Asignatura", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        jLabel1.setText("Nombre");

        txtNombre.setColumns(15);

        jLabel2.setText("Codigo");

        jLabel3.setText("Creditos");

        jsCreditos.setModel(new javax.swing.SpinnerNumberModel(1, 1, 12, 1));

        jLabel4.setText("Periodo");

        jLabel5.setText("Requisito");

        jLabel6.setText("Coreq.");

        jLabel7.setText("Nota");

        jLabel8.setText("Nivel");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                    .addComponent(jsCreditos, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE)
                    .addComponent(txtCodigo)
                    .addComponent(txtNota, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtPeriodo)
                    .addComponent(txtReq)
                    .addComponent(txtCoreq)
                    .addComponent(txtNivel))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jsCreditos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtPeriodo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtNivel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtReq, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtCoreq, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtNota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    public Asignatura getA() throws Exception, NumberFormatException, NullPointerException {
        String nom = txtNombre.getText();
        if (nom.isEmpty()) {
            throw new Exception("Nombre no puede ser vacio.");
        }
        String cod = txtCodigo.getText();
        if (cod.isEmpty()) {
            throw new Exception("Codigo no puede ser vacio.");
        }
        String per = txtPeriodo.getText();
        String niv = txtNivel.getText();
        String req = txtReq.getText();
        String cor = txtCoreq.getText();
        Asignatura areq = null;
        Asignatura acor = null;
        if (null != p) {
            areq = (null == p.getPlan().buscarPeriodoAnteriorA(p)) ? null : p.getPlan().buscarAsignaturaPorCodigo(req);
            acor = (p.vacio()) ? null : p.buscarAsignaturaPorCodigo(cor);
        }

        int cre = (int) jsCreditos.getValue();
        double not = Double.parseDouble(txtNota.getText());

        boolean m = (null != a) ? a.isMatriculada() : false;
        a = new Asignatura(nom, cod, cre, per, niv, areq, acor, not);
        a.setMatriculada(m);
        return a;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JSpinner jsCreditos;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtCoreq;
    private javax.swing.JTextField txtNivel;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtNota;
    private javax.swing.JTextField txtPeriodo;
    private javax.swing.JTextField txtReq;
    // End of variables declaration//GEN-END:variables
}
